// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
  RelationKeys,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'97d8d2efdb742858bf44d6a35996a98d6902373ede663eee9e2baabef6599cdb'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Chats: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly role: CodecTypes['mongo/string@1']['output'];
      readonly content: CodecTypes['mongo/string@1']['output'];
      readonly chatSessionId: CodecTypes['mongo/objectId@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly ChatSession: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly userId: CodecTypes['mongo/objectId@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly UploadedPdf: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly documentId: CodecTypes['mongo/string@1']['output'];
      readonly key: CodecTypes['mongo/string@1']['output'];
      readonly fileName: CodecTypes['mongo/string@1']['output'];
      readonly userId: CodecTypes['mongo/objectId@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly email: CodecTypes['mongo/string@1']['output'];
      readonly googleId: CodecTypes['mongo/string@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'] | null;
      readonly image: CodecTypes['mongo/string@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Chats: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly role: CodecTypes['mongo/string@1']['input'];
      readonly content: CodecTypes['mongo/string@1']['input'];
      readonly chatSessionId: CodecTypes['mongo/objectId@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly ChatSession: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly userId: CodecTypes['mongo/objectId@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly UploadedPdf: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly documentId: CodecTypes['mongo/string@1']['input'];
      readonly key: CodecTypes['mongo/string@1']['input'];
      readonly fileName: CodecTypes['mongo/string@1']['input'];
      readonly userId: CodecTypes['mongo/objectId@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly email: CodecTypes['mongo/string@1']['input'];
      readonly googleId: CodecTypes['mongo/string@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'] | null;
      readonly image: CodecTypes['mongo/string@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
  };
};

export namespace Models {
  export type unbound_User = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    email: CodecTypes['mongo/string@1']['output'];
    googleId: CodecTypes['mongo/string@1']['output'];
    name: CodecTypes['mongo/string@1']['output'] | null;
    image: CodecTypes['mongo/string@1']['output'] | null;
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    uploadedpdf: unbound_UploadedPdf[];
    chatSessions: unbound_ChatSession[];
    readonly [RelationKeys]?: 'uploadedpdf' | 'chatSessions';
  };
  export type unbound_UploadedPdf = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    documentId: CodecTypes['mongo/string@1']['output'];
    key: CodecTypes['mongo/string@1']['output'];
    fileName: CodecTypes['mongo/string@1']['output'];
    userId: CodecTypes['mongo/objectId@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    uploadedBy: unbound_User;
    readonly [RelationKeys]?: 'uploadedBy';
  };
  export type unbound_ChatSession = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    name: CodecTypes['mongo/string@1']['output'];
    userId: CodecTypes['mongo/objectId@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    user: unbound_User;
    chats: unbound_Chats[];
    readonly [RelationKeys]?: 'user' | 'chats';
  };
  export type unbound_Chats = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    role: CodecTypes['mongo/string@1']['output'];
    content: CodecTypes['mongo/string@1']['output'];
    chatSessionId: CodecTypes['mongo/objectId@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    chatSession: unbound_ChatSession;
    readonly [RelationKeys]?: 'chatSession';
  };
}

export declare const models: {
  __unbound__: {
    User: Models.unbound_User;
    UploadedPdf: Models.unbound_UploadedPdf;
    ChatSession: Models.unbound_ChatSession;
    Chats: Models.unbound_Chats;
  };
};

export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly chats: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly role: { readonly bsonType: 'string' };
                    readonly content: { readonly bsonType: 'string' };
                    readonly chatSessionId: { readonly bsonType: 'objectId' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'chatSessionId',
                    'content',
                    'createdAt',
                    'role',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly chatSession: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly userId: { readonly bsonType: 'objectId' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'createdAt', 'name', 'updatedAt', 'userId'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly uploadedPdf: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly documentId: { readonly bsonType: 'string' };
                    readonly key: { readonly bsonType: 'string' };
                    readonly fileName: { readonly bsonType: 'string' };
                    readonly userId: { readonly bsonType: 'objectId' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'createdAt',
                    'documentId',
                    'fileName',
                    'key',
                    'updatedAt',
                    'userId',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly user: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'email'; readonly direction: 1 }];
                  readonly unique: true;
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'googleId'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly email: { readonly bsonType: 'string' };
                    readonly googleId: { readonly bsonType: 'string' };
                    readonly name: { readonly bsonType: readonly ['null', 'string'] };
                    readonly image: { readonly bsonType: readonly ['null', 'string'] };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'createdAt',
                    'email',
                    'googleId',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly user: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly uploadedPdf: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'UploadedPdf';
    };
    readonly chatSession: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'ChatSession';
    };
    readonly chats: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Chats' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Chats: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly chatSessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly chatSession: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'ChatSession';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['chatSessionId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'chats' };
          };
          readonly ChatSession: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly chats: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Chats';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['chatSessionId'];
                };
              };
            };
            readonly storage: { readonly collection: 'chatSession' };
          };
          readonly UploadedPdf: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly documentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly fileName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly uploadedBy: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'uploadedPdf' };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly googleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly uploadedpdf: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'UploadedPdf';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly chatSessions: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'ChatSession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: { readonly collection: 'user' };
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
